import json
import time
from utils.claude_client import call_claude, is_mock_mode
from utils.mock_data import MOCK_REPORT_RESPONSE

SYSTEM_PROMPT = """You are a senior technical writer producing a professional technology 
recommendation report. Given project requirements, evaluated technology options with 
scores, and metadata about the evaluation process, produce a clear Markdown report.

The report MUST follow this exact structure:

# Tech Stack Recommendation Report

## Project Overview
(Summarize the project and key requirements in 2-3 sentences)

## Recommended Stack

### Frontend
**Recommendation: [Name]** (Score: X.X/10)
- Why: (2-3 sentences explaining the choice)
- Runner-up: [Name] (Score: X.X/10) — tradeoff explanation

### Backend
(same structure)

### Database
(same structure)

### Hosting
(same structure)

### Authentication
(same structure)

## Stack Synergy
(1 paragraph explaining how these technologies work well together)

## Tradeoffs & Risks
(Bullet points covering key risks and what to watch out for)

## Areas of Uncertainty
(If any categories had low confidence even after re-evaluation, 
acknowledge them here. If all categories are strong, say so.)

## Evaluation Metadata
- Iterations completed: X
- Confidence threshold: 7.0/10
- Categories that required re-research: [list or "none"]

---
*Generated by Tech Stack Recommender — an agentic AI system*

Rules:
- Use the HIGHEST-SCORING option as the recommendation per category
- Be specific — reference actual scores and requirements
- If a category was flagged as weak and never improved, be HONEST about it
- Write for a developer audience — be practical, not salesy
- Output ONLY the Markdown report. No preamble, no code fences around the whole thing."""


def reporter_agent(state: dict) -> dict:
    if is_mock_mode():
        time.sleep(1.5)
        state["final_report"] = MOCK_REPORT_RESPONSE
        return state

    requirements = state["requirements"]
    options = state["options"]
    scores = state["scores"]
    weak_categories = state.get("weak_categories", [])
    iteration_count = state.get("iteration_count", 0)

    user_message = (
        f"Project requirements:\n"
        f"```json\n{json.dumps(requirements, indent=2)}\n```\n\n"
        f"Technology options:\n"
        f"```json\n{json.dumps(options, indent=2)}\n```\n\n"
        f"Evaluation scores:\n"
        f"```json\n{json.dumps(scores, indent=2)}\n```\n\n"
        f"Evaluation metadata:\n"
        f"- Total feedback iterations: {iteration_count}\n"
        f"- Categories still weak after all iterations: {weak_categories if weak_categories else 'none'}\n"
        f"- Confidence threshold used: 7.0/10\n\n"
        f"Generate the full Markdown recommendation report."
    )

    report = call_claude(
        system_prompt=SYSTEM_PROMPT,
        user_message=user_message,
        max_tokens=4096,
    )

    state["final_report"] = report
    return state
